version: "3.7"
services:
  #Laravel Service
  app:
    container_name: laravel_react_app
    restart: always
    tty: true
    working_dir: /var/www/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: "idekey=IDE_DEBUG"
      PHP_IDE_CONFIG: "serverName=laravel_react_app"
#    ports:
#      - 9001:9000
#      - 9002:9001
    volumes:
      - .:/var/www/app
    depends_on:
      - database
    links:
      - database
    networks:
      - laravel_react_network

  #MySQL Service
  database:
    image: mysql:5.7
    container_name: laravel_react_database
    restart: always
    tty: true
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: formassembly
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: cylord
      MYSQL_PASSWORD: sherrod
    volumes:
      #- dbdata2:/var/lib/mysql/
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel_react_network

  #Nginx Service
  server:
    image: nginx:1.13
    container_name: laravel_react_server
    restart: always
    tty: true
    ports:
      - 8100:8080
    volumes:
      - .:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    networks:
      - laravel_react_network

#Docker Networks
networks:
  laravel_react_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
